apiVersion: v1
kind: Service
metadata:
  name: innsight-backend
  labels:
    app: innsight-backend
spec:
  type: NodePort
  selector:
    app: innsight-backend
  ports:
    - protocol: TCP
      port: 80          # puerto del servicio dentro del cluster
      targetPort: 5000  # puerto del contenedor
      nodePort: 30080   # puerto expuesto en el nodo (accesible desde fuera)
